project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!assignments*/*.qmd"  # Don't render homework qmd files

website:
  title: "Sociology 106"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Slides"
        href: slides/index.qmd
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Assignments"
        href: assignments/index.qmd

format:
  html:
    theme: flatly
    css: styles.css
