project:
  type: website
  output-dir: docs

website:
  title: "Sociology 106"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Slides"
        href: slides/index.qmd
      - text: "Syllabus"
        href: syllabus.qmd

format:
  html:
    theme: lux
    css: styles.css
